export const QUESTIONS = [
  { id: 1, text: `“Some bees make honey” is translated as $(\\exists x)(Bx \\cdot Hx)$.`, correct: 'T' },
  { id: 2, text: `The universal quantifier is used when a statement applies to every member of the subject class.`, correct: 'T' },
  { id: 3, text: `$(x)(Fx)$ claims that every $x$ is $F$.`, correct: 'T' },
  { id: 4, text: `“Aliens exist” translates to $(x)Ax$.`, correct: 'F' },
  { id: 5, text: `“Cowards die many times before their deaths; the valiant never taste of death but once.” is translated as $(x)(Cx\\supset Dx) \\cdot (\\exists x)(Vx \\cdot Nx)$.`, correct: 'F' },
  { id: 6, text: `$(\\exists x)Fx$ claims that some $x$ is $F$.`, correct: 'T' },
  { id: 7, text: `“All dogs are mammals” is translated as $(x)(Dx \\supset Mx)$.`, correct: 'T' },
  { id: 8, text: `“Jane is a florist” → $Fj$`, correct: 'T' },
  { id: 9, text: `The letter $a$ may be used as an individual constant to represent a particular person.`, correct: 'T' },
  { id: 10, text: `“Only bees make honey” translates to $(x)(Bx \\supset Hx)$.`, correct: 'F' },
  { id: 11, text: `Free variables occur when no quantifier governs the variable.`, correct: 'T' },
  { id: 12, text: `“No bees (B) make honey (H)” is translated as $(x)(Bx \\supset \\sim Hx)$.`, correct: 'T' },
  { id: 13, text: `“Some bees make honey” is translated as $(\\exists x)(Bx \\supset Hx)$.`, correct: 'F' },
  { id: 14, text: `The individual variable $x$ refers to a specific named individual in the domain.`, correct: 'F' },
  { id: 15, text: `The existential quantifier is used when a statement applies to at least one member of the subject class.`, correct: 'T' },
  { id: 16, text: `The variable in a quantifier expression can be replaced by any other variable without changing meaning, as long as usage is consistent.`, correct: 'T' },
  { id: 17, text: `$(x)(Fx)$ means “at least one thing is $F$.”`, correct: 'F' },
  { id: 18, text: `“None but bees make honey” translates to $(x)(Hx \\supset Bx)$.`, correct: 'T' },
  { id: 19, text: `Using $(\\exists x)(Sx \\supset Px)$ to translate “Some S are P” produces a statement with different truth conditions than intended.`, correct: 'T' },
  { id: 20, text: `$(x)(Fx \\cdot Gx)$ is equivalent to $(x)(Fx) \\cdot (x)(Gx)$.`, correct: 'T' },
  { id: 21, text: `“There are no aliens” translates to $(x)\\sim Ax$.`, correct: 'T' },
  { id: 22, text: `$(\\exists x)(Fx)$ means that everything is $F$.`, correct: 'F' },
  { id: 23, text: `Confusing $(x)$ and $(\\exists x)$ usually changes the truth conditions of the translated statement.`, correct: 'T' },
  { id: 24, text: `$(x)(Fx \\supset Gx)$ does not assert that anything is $F$.`, correct: 'T' },
  { id: 25, text: `“No allies are secure in wartime” may be expressed as $(\\exists x)\\sim(Ax \\cdot Sx)$.`, correct: 'F' },
  { id: 26, text: `“Only bees make honey” translates to $(x)(Hx \\supset Bx)$.`, correct: 'T' },
  { id: 27, text: `"Every statement has a truth value."`, correct: 'T' },
  { id: 28, text: `“All dogs (D) are mammals (M)” is translated as $(x)(Dx \\cdot Mx)$.`, correct: 'F' },
  { id: 29, text: `A singular statement such as “Van Gogh is a painter” is translated using a constant, not a variable.`, correct: 'T' },
  { id: 30, text: `Universal quantifiers are used to translate singular statements.`, correct: 'F' },
  { id: 31, text: `Existential quantifiers are used to translate singular statements.`, correct: 'F' },
  { id: 32, text: `“Jane is a florist” → $(x)Fx$`, correct: 'F' },
  { id: 33, text: `The word “some” always requires a conjunction inside the quantifier expression.`, correct: 'F' },
  { id: 34, text: `The word “every” always requires a conditional inside the quantifier expression.`, correct: 'F' },
  { id: 35, text: `The form $(\\exists x)(Fx) \\cdot (\\exists x)(Px)$ asserts that possibly different individuals are $F$ and $P$.`, correct: 'T' },
  { id: 36, text: `The form $(\\exists x)(Fx \\cdot Px)$ asserts that the same individual is both $F$ and $P$.`, correct: 'T' },
  { id: 37, text: `A universal statement is normally translated as a conditional.`, correct: 'T' },
  { id: 38, text: `$Fa$ claims that $a$ is $F$.`, correct: 'T' },
  { id: 39, text: `Misplacing parentheses can change which expression is governed by a quantifier.`, correct: 'T' },
  { id: 40, text: `“There are no aliens” translates to $(\\exists x)\\sim Ax$.`, correct: 'F' }
]
